01-FrontEnd/ViewModels/LessonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FrontEnd.ViewModels
{
    public class LessonCreateViewModel
    {
        [Required]
        public int CourseId { get; set; }

        [Required]
        public string Name { get; set; }

    }

    public class LessonUpdateViewModel {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Content { get; set; }

        public string Video { get; set; }
    }
}

01-FrontEnd/Controllers/LearnController.cs
using Common;
using Common.ProjectHelpers;
using Service;
using System.IO;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    [Authorize(Roles = RolNames.Student)]
    public class LearnController : Controller
    {
        private IStudentService _studentService = DependecyFactory.GetInstance<IStudentService>();

        [Route("learn/{id}/{lessonId?}")]
        public ActionResult Index(int id, int lessonId = 0)
        {
            return View(
                _studentService.Get(
                    id,
                    lessonId,
                    CurrentUserHelper.Get.UserId
                )
            );
        }

        [HttpPost]
        [Route("learn/MarkAsLearned")]
        public JsonResult MarkAsLearned(int lessonId, int courseId)
        {
            var rh = _studentService.MarkAsLearned(
                courseId,
                lessonId,
                CurrentUserHelper.Get.UserId
            );

            if (rh.Response)
            {
                rh.Href = "self";
            }

            return Json(
                rh
            );
        }
    }

    
}

01-FrontEnd/Views/Learn/Partials/_Actions.cshtml
@model LessonLandingPage


<h3>Acciones disponibles</h3>

@using (Html.BeginForm("MarkAsLearned", "Learn", FormMethod.Post))
{
    <input type="hidden" name="lessonId" value="@Model.Id" />
    <input type="hidden" name="courseId" value="@Model.CourseId" />

    <div class="alert-container"></div>

    <button data-ajax="true" type="submit" class="btn btn-success btn-block btn-lg">
        Marcar como aprendido <i class="fa fa-check"></i>
    </button>
}

01-FrontEnd/Views/Learn/Partials/_Lessons.cshtml
@model LessonLandingPage

<h3>Temario</h3>
<ul class="list-group">
    @foreach (var m in Model.Lessons)
    {
        <li class="list-group-item @(Model.Id == m.Id ? "active" : "")">
            <div class="row">
                <div class="col-xs-9 col-sm-10">
                    <b>#@(Model.Lessons.IndexOf(m) + 1)</b> <a href="~/learn/@m.CourseId/@m.Id">@m.Name</a>
                </div>
                @if (m.Learned)
                {
                    <div class="col-xs-3 col-sm-2 text-right">
                        <span class="badge">
                            <i class="fa fa-check"></i>
                        </span>
                    </div>
                }
            </div>
        </li>
    }
</ul>

01-FrontEnd/Views/Learn/Partials/_Page.cshtml
@model LessonLandingPage

<h3>@Model.Name</h3>
<div class="panel panel-default">
    <div class="panel-body text-justify">
        @if (Model.HasVideo)
        {
            <div class="embed-responsive embed-responsive-16by9 video-target"></div>
        }
        <div id="markdown">
            @Html.Raw(Model.Content)
        </div>
    </div>
</div>