01-FrontEnd/Controllers/StudyingController.cs
using Common;
using FrontEnd.App_Start;
using FrontEnd.ViewModels;
using Model.Domain;
using Service;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    [Authorize]
    public class StudyingController : Controller
    {
        private IStudentService _studentService = DependecyFactory.GetInstance<IStudentService>();

        public ActionResult Index()
        {
            return View(
                _studentService.GetAll(CurrentUserHelper.Get.UserId)
            );
        }

        public JsonResult Review(ReviewViewModel model)
        {
            var rh = new ResponseHelper();

            if (!ModelState.IsValid)
            {
                var validations = ModelState.GetErrors();
                rh.SetValidations(validations);
            }
            else
            {
                rh = _studentService.Review(new ReviewPerCourse
                {
                    Comment = model.Comment,
                    Vote = model.Vote,
                    UserId = CurrentUserHelper.Get.UserId,
                    CourseId = model.CourseId
                });

                if (rh.Response)
                {
                    rh.Href = "self";
                }
            }

            return Json(rh);
        }
    }
}

01-FrontEnd/Views/Studying/Index.cshtml
@model IEnumerable<CoursePerStudentListView>

@{
    ViewBag.Title = "Mis cursos";
}
<h1 class="page-header">
    @ViewBag.Title
</h1>

<div class="list-group list-group-courses">
    @foreach (var m in Model)
    {
        <div class="list-group-item">
            <div class="progress" data-toggle="tooltip" data-placement="top" title="Completado al @(m.Progress)%">
                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="@m.Progress" aria-valuemin="0" aria-valuemax="100" style="width: @(m.Progress)%">
                    @(m.Progress)% Completado
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <a href="~/learn/@m.Id">
                        <img class="img-responsive" src="~/@m.Image" alt="@m.Name" />
                    </a>
                </div>
                <div class="col-sm-8 ">
                    <h4>
                        <a href="~/learn/@m.Id">
                            @m.Name
                        </a>
                    </h4>
                    <p class="text-justify">
                        @m.Description
                    </p>
                </div>
                <div class="col-sm-2">
                    <a href="~/learn/@m.Id" class="btn btn-primary btn-block">
                        <i class="fa fa-right"></i> Ingresar
                    </a>
                    @if (!m.HaveVotes)
                    {
                        <button type="button" class="btn btn-default btn-block course-review" value="@m.Id">
                            <i class="fa fa-star"></i> Valorar
                        </button>
                    }
                </div>
            </div>
        </div>
    }
</div>

<div class="modal fade" id="ratingModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("Review", "Studying", FormMethod.Post))
        {
            <input type="hidden" name="CourseId" id="CourseId" />
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Valorar curso</h4>
                </div>
                <div class="modal-body">
                    <div class="alert-container"></div>
                    <div class="form-group">
                        <label>Comentario</label>
                        <textarea id="reviewComment" class="form-control" name="Comment"></textarea>
                        <span data-key="Comment" class="form-validation-failed"></span>
                    </div>
                    <div class="form-group">
                        <label>Valoración</label>
                        <select id="reviewVote" class="form-control" name="Vote">
                            @for (var i = 1; i <= 10; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit"
                            data-ajax="true"
                            class="btn btn-success">
                        <i class="fa fa-star"></i> Valorar
                    </button>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $(".course-review").click(function () {
                $("#ratingModal").modal();
                $("#CourseId").val($(this).val());
                $("#reviewComment").val('');
                $("#reviewVote").val('10');
            })
        })
    </script>
}

01-FrontEnd/Views/Studying/_Review.cshtml
<div class="modal fade" id="ratingModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm("Review", "Styuding", FormMethod.Post))
        {
            <input type="hidden" name="CourseID" />
            <input type="hidden" name="UserID" />
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Confirmación de pago</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Comentario</label>
                        <textarea class="form-control" name="Comment"></textarea>
                    </div>
                    <div class="form-group">
                        <label>Valoración</label>
                        <select class="form-control" name="Vote">
                            @for (var i = 1; i <= 10; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit"
                            data-ajax="true"
                            class="btn btn-success">
                        <i class="fa fa-star"></i> Valorar
                    </button>
                </div>
            </div>
        }
    </div>
</div>