01-FrontEnd/ViewModels/CourseViewModel.cs
using Model.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FrontEnd.ViewModels
{
    public class CourseBasicInformationViewModel
    {
        public Course Course { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

01-FrontEnd/ViewModels/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FrontEnd.ViewModels
{
    public class UserBasicInformationViewModel
    {
        [Required]
        public string Id { get; set; }

        [Required]
        [Display(Name="Nombre")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Apellido")]
        public string LastName { get; set; }
    }
}

01-FrontEnd/Controllers/CourseController.cs
using Common;
using Service;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    public class CourseController : Controller
    {
        private ICourseService _courseService = DependecyFactory.GetInstance<ICourseService>();
        private ICategoryService _categoryService = DependecyFactory.GetInstance<ICategoryService>();

        [Route("course/{id}/{slug}")]
        public ActionResult Index(int id, string slug)
        {
            return View(_courseService.GetForLandingPage(id));
        }

        [Route("category/{id}/{slug}")]
        public ActionResult Category(int id, string slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return Redirect("~");
            }

            var model = _categoryService.Get(id);

            ViewBag.Title = model.Name;
            return View(model);
        }

        [HttpPost]
        public JsonResult All(int categoryId) {

            return Json(_courseService.GetAll(categoryId));
        }

        [HttpPost, Authorize]
        public JsonResult Purchase(int courseId) {

            var rh = _courseService.Purchase(courseId, CurrentUserHelper.Get.UserId);

            if (rh.Response) {
                rh.Href = "studying";
            }

            return Json(rh);
        }
    }
}

01-FrontEnd/Controllers/PanelController.cs
using Common;
using FrontEnd.App_Start;
using Service;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    [Authorize(Roles = RolNames.Admin)]
    public class PanelController : Controller
    {
        private IUserService _userService = DependecyFactory.GetInstance<IUserService>();
        private ICategoryService _categoryService = DependecyFactory.GetInstance<ICategoryService>();
        private IWidgetService _widgetService = DependecyFactory.GetInstance<IWidgetService>();
        private ICourseService _courseService = DependecyFactory.GetInstance<ICourseService>();
        // GET: Course
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Categories()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetCategory(int id) {

            return Json(_categoryService.Get(id));
        }

        [HttpPost]
        public JsonResult GetCategories(AnexGRID grid)
        {

            return Json(_categoryService.GetAll(grid));
        }


        [HttpPost]
        public JsonResult Category(int id = 0)
        {
            return Json(null);
        }

        [HttpPost]
        public JsonResult CategorySave(Model.Domain.Category model)
        {
            var rh = new ResponseHelper();

            if (!ModelState.IsValid)
            {
                var validations = ModelState.GetErrors();
                rh.SetValidations(validations);
            }
            else {
                rh = _categoryService.InsertOrUpdate(model);
                if (rh.Response) {

                    rh.Href = "self";
                }
            }

            return Json(rh);
        }

        //public ActionResult Courses()
        //{
        //    return View();
        //}

        public ActionResult Users()
        {
            return View();
        }

       [HttpPost]
        public JsonResult GetUsers(AnexGRID grid) {
            return Json(
                    _userService.GetAll(grid)
                );
        }

        #region Widget
        [HttpPost]
        public JsonResult WidgetGetIncomes(bool month)
        {
            return Json(
                _widgetService.Incomes(month)
            );
        }

        [HttpPost]
        public JsonResult WidgetGetVariance()
        {
            return Json(
                _widgetService.Variance()
            );
        }

        [HttpPost]
        public JsonResult WidgetGetAverage()
        {
            return Json(
                _widgetService.Average()
            );
        }
        #endregion

        #region Course
        public ActionResult Courses()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetCourses(AnexGRID grid)
        {
            return Json(
                _courseService.GetAll(grid)
            );
        }

        [HttpPost]
        public JsonResult ChangeStatusByCourse(int id, Enums.Status status)
        {
            return Json(
                _courseService.ChangeStatus(id, status)
            );
        }
        #endregion
    }
}

01-FrontEnd/Controllers/UserController.cs
using Common;
using Service;
using System.Web.Mvc;

namespace FrontEnd.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private IUserService _userService = DependecyFactory.GetInstance<IUserService>();
        [HttpPost]
        public JsonResult GetCreditsByCurrentUser() {

            return Json(_userService.GetCredits(
                    CurrentUserHelper.Get.UserId
                ));
        }
    }
}

01-FrontEnd/Views/Panel/Categories.cshtml
@{
    ViewBag.Title = "Categorías";
}
<h1 class="page-header">
    <button id="category-new" type="button" class="btn btn-default pull-right btn-sm">
        <i data-toggle="tooltip" data-placement="top" title="Nueva categoría" class="fa fa-plus"></i>
    </button>
    @ViewBag.Title
</h1>

@Html.Partial("Partials/_Menu", Enums.PanelMenu.Categories)

<div id="list"></div>



<!-- Modal -->
<div class="modal fade" id="category-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            @using (Html.BeginForm("CategorySave", "Panel", FormMethod.Post))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Categoría</h4>
                </div>
                <div class="modal-body">
                    <category url="@Url.Action("GetCategory","Panel")"></category>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                    <button type="submit" data-ajax="true" class="btn btn-primary">Guardar</button>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {

    <script src="~/Assets/vue_components/dist/category.components.js"></script>
    <script>
$(document).ready(function () {
    let conf = {
        class: 'table-striped table-bordered',
        columnas: [
            { leyenda: 'Icon', columna: 'Icon', style: 'width:40px;' },
            { leyenda: 'Nombre', columna: 'Name' },
            { leyenda: 'Cursos', style: 'width:100px;', columna: 'Courses' },
            { leyenda: 'Alumnos', style: 'width:100px;', columna: 'Students' },
            { leyenda: 'Eliminar', style: 'width:40px;' },
            { leyenda: 'Editar', style: 'width:40px;' }
        ],
        modelo: [
            {
                propiedad: 'Icon', formato: function (tr, obj, value) {
                    return '<i class="fa fa-' + value + '"></i>';
                }
            },
            { propiedad: 'Name' },
            { propiedad: 'Courses' },
            { propiedad: 'Students' },
            {
                propiedad: 'Id', formato: function (tr, obj, value) {
                    return '<button value="' + value + '" type="button" class="btn btn-danger category-delete"><i class="fa fa-trash"></i></button>';
                }
            },
            {
                propiedad: 'Id', formato: function (tr, obj, value) {
                    return '<button value="' + value + '" type="button" class="btn btn-primary category-edit"><i class="fa fa-edit"></i></button>';
                }
            },
        ],
        url: '@Url.Action("GetCategories", "Panel")',
        limite: 20,
        paginable: true,
        columna: 'Name',
        columna_orden: 'ASC'
    };

    let grid = $("#list").anexGrid(conf);

    grid.tabla().on('click', '.category-edit', function() {
        let value = $(this).val();
        $("#category-edit").modal('show');
        $Vm.$emit('categorySelectedID', value);
    })

    @*grid.tabla().on('click', '.category-delete', function () {
        let value = $(this).val();

        if (!confirm('Esta seguro de eliminar este registro?')) return;

        $.post('@Url.Action("DeleteCategory", "Panel")', {
            id: value
        }, function(r) {
            if (!r.Response) {
                alert(r.Message)
            } else {
                grid.refrescar();
            }
        }, 'json')
    })*@

    $("#category-new").click(function() {
        $("#category-edit").modal('show');
        $Vm.$emit('categorySelectedID', 0);
    })
})
    </script>
}

01-FrontEnd/Views/Panel/Courses.cshtml
@{
    ViewBag.Title = "Cursos";
}
<h1 class="page-header">@ViewBag.Title</h1>

@Html.Partial("Partials/_Menu", Enums.PanelMenu.Courses)

<div id="list"></div>

@section Scripts {
    <script>
    $(document).ready(function () {
        let options = [];

        for (var k in Enums.Status) {
            options.push({
                value: Enums.Status[k].value,
                description: Enums.Status[k].description
            });
        }

        let conf = {
            class: 'table-striped table-bordered',
            columnas: [
                { leyenda: 'Nombre', columna: 'Name' },
                { leyenda: 'Instructor', style: 'width:300px;', columna: 'Instructor' },
                { leyenda: 'Alumnos', style: 'width:100px;', columna: 'Students' },
                { leyenda: 'Lecciones', style: 'width:100px;', columna: 'Lessons' },
                { leyenda: 'Estado', style: 'width:200px;', columna: 'Status' },
            ],
            modelo: [
                { propiedad: 'Name' },
                { propiedad: 'Instructor' },
                { propiedad: 'Students' },
                { propiedad: 'Lessons' },
                {
                    propiedad: 'Status', formato: function (tr, obj, value) {
                        let div = $('<div />'),
                            select = $('<select data-id="' + obj.Id + '" class="form-control input-xs course-status" />');

                        options.forEach(function (x) {
                            let o = $('<option value="' + x.value + '" />');
                            o.text(x.description);

                            if (x.value === value) {
                                o.attr('selected', true);
                            }

                            select.append(o);
                        })

                        div.append(select);
                        return div.html();
                    }
                },
            ],
            url: '@Url.Action("GetCourses", "Panel")',
        limite: 20,
        paginable: true,
        columna: 'Name',
        columna_orden: 'ASC'
    };

    let grid = $("#list").anexGrid(conf);

    grid.tabla().on('change', '.course-status', function () {
        debugger;
        let value = $(this).val(),
            courseId = $(this).data('id');

        if (!confirm('Esta seguro cambiar el estado actual?')) return;

        $.post('@Url.Action("ChangeStatusByCourse", "Panel")', {
            id: courseId,
            status: value
        }, function(r) {
            if (!r.Response) {
                alert(r.Message)
            } else {
                grid.refrescar();
            }
        }, 'json')
    })
})
    </script>
}

01-FrontEnd/Views/Panel/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}
<h1 class="page-header">@ViewBag.Title</h1>

@Html.Partial("Partials/_Menu", Enums.PanelMenu.Home)

<h2 class="page-header">Ingresos</h2>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Ingreso Total
                <span class="badge pull-right">
                    <i class="fa fa-line-chart"></i>
                </span>
            </div>
            <widgetincome :month="false"></widgetincome>
            @*<ul class="list-group">
                <li class="list-group-item">
                    Ingreso Total (100 %)<span class="badge">$ 12,500.25</span>
                </li>
                <li class="list-group-item">
                    Ingreso @Parameters.ProjectName (@(Parameters.SalesCommission)%) <span class="badge">$ 5,250.12</span>
                </li>
                <li class="list-group-item">
                    Pago a profesores (@(100 - Parameters.SalesCommission)%) <span class="badge">$ 7,250.12</span>
                </li>
            </ul>*@
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Ingreso del mes actual
                <span class="badge pull-right">
                    <i class="fa fa-calendar"></i>
                </span>
            </div>
            <widgetincome :month="true"></widgetincome>
            @*<ul class="list-group">
                <li class="list-group-item">
                    Ingreso Total (100 %)<span class="badge">$ 2,500.25</span>
                </li>
                <li class="list-group-item">
                    Ingreso @Parameters.ProjectName (@(Parameters.SalesCommission)%) <span class="badge">$ 750.12</span>
                </li>
                <li class="list-group-item">
                    Pago a profesores (@(100 - Parameters.SalesCommission)%) <span class="badge">$ 1,750.12</span>
                </li>
            </ul>*@
        </div>
    </div>
</div>

<h2 class="page-header">Estadística</h2>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Variación Porcentual (Mes actual)
                <span class="badge pull-right">
                    <i class="fa fa-line-chart"></i>
                </span>
            </div>
            <widgetvariance></widgetvariance>
            @*<ul class="list-group">
                <li class="list-group-item">
                    Ingreso @Parameters.ProjectName <span class="badge"><i class="fa fa-level-up"></i> 25%</span>
                </li>
                <li class="list-group-item">
                    Alumnos <span class="badge"><i class="fa fa-level-up"></i> 25%</span>
                </li>
                <li class="list-group-item">
                    Profesores <span class="badge"><i class="fa fa-level-up"></i> 25%</span>
                </li>
                <li class="list-group-item">
                    Cursos creados <span class="badge"><i class="fa fa-level-up"></i> 25%</span>
                </li>
            </ul>*@
        </div>
    </div>
    <div class="col-sm-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Media aritmética (Por mes)
                <span class="badge pull-right">
                    <i class="fa fa-bar-chart"></i>
                </span>
            </div>
            <widgetaverage></widgetaverage>
            @*<ul class="list-group">
                <li class="list-group-item">
                    Ingreso @Parameters.ProjectName <span class="badge">$ 100,200.00</span>
                </li>
                <li class="list-group-item">
                    Alumnos <span class="badge">100</span>
                </li>
                <li class="list-group-item">
                    Profesores <span class="badge">7</span>
                </li>
                <li class="list-group-item">
                    Cursos creados <span class="badge">7</span>
                </li>
            </ul>*@
        </div>
    </div>
</div>

@section Scripts{
  
<script src="~/Assets/vue_components/dist/widget.components.js"></script>  
    }

01-FrontEnd/Views/Panel/Users.cshtml
@{
    ViewBag.Title = "Usuarios";
}
<h1 class="page-header">@ViewBag.Title</h1>

@Html.Partial("Partials/_Menu", Enums.PanelMenu.Users)

@*<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>Nombre</th>
            <th style="width:200px;">Correo</th>
            <th style="width:300px;">Roles</th>
            <th class="text-right" style="width:150px;">Cursos inscritos</th>
            <th class="text-right" style="width:150px;">Cursos creados</th>
        </tr>
    </thead>
    <tbody>
        @for (var i = 1; i < 20; i++)
        {
            <tr>
                <td>Usuario @i</td>
                <td>@i-user@anexu.com</td>
                <td>User, Teacher, Student</td>
                <td class="text-right">@(i * 3)</td>
                <td class="text-right">@(i * 2)</td>
            </tr>
        }
    </tbody>
</table>*@

<div id="list"></div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var conf = {
                class: 'table-striped table-bordered',
                columnas: [
                    { leyenda: 'Nombre', columna: 'FullName' },
                    { leyenda: 'Correo', columna: 'Email'},
                    { leyenda: 'Roles', style: 'width:300px;'},
                    { leyenda: 'Cursos inscritos', style: 'width:150px;', columna: 'CoursesTaken' },
                    { leyenda: 'Cursos creados', style: 'width:150px;', columna: 'CoursesCreated' }
                ],
                modelo: [
                    { propiedad: 'FullName' },
                    { propiedad: 'Email' },
                    {
                        propiedad: 'Roles', formato: function (tr, obj, value) {
                            return value.join(', ');
                        }
                    },
                    { propiedad: 'CoursesTaken' },
                    { propiedad: 'CoursesCreated' }
                   
                ],
                url: '@Url.Action("GetUsers","Panel")',
                limite: 20,
                paginable: true,
                columna: 'FullName',
                columna_orden: 'ASC'
            };

            $("#list").anexGrid(conf);
        })
    </script>
    }